config/routes.rb
Rails.application.routes.draw do
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    root 'sample#index'
    get 'index',                    to: 'sample#index'
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
    resources :products,          only: [:show]
    resources :categories,        only: [:show]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/spree/product_decorator.rb
Spree::Product.class_eval do
  scope :related_products, lambda { |product|
    includes_images_price.
      joins(:classifications).
      where(spree_products_taxons: { taxon_id: product.taxon_ids })
  }
  scope :includes_images_price, -> { includes(master: [:images, :default_price]) }
  scope :excludes, ->(product) { where.not(id: product) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/potepan/categories_controller.rb
class Potepan::CategoriesController < ApplicationController
  def show
    @taxon = Spree::Taxon.find(params[:id])
    @taxonomies = Spree::Taxonomy.all
    @products = Spree::Product.includes(master: [:images, :default_price]).in_taxon(@taxon)
  end
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  RELATED_PRODUCTS_LIMIT = 8

  def show
    @product = Spree::Product.find(params[:id])
    @related_products = Spree::Product.
      related_products(@product).
      limit(RELATED_PRODUCTS_LIMIT).
      distinct.
      excludes(@product)
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  def index
    @taxonomies = Spree::Taxonomy.all
    render :layout => false
  end

  def product_grid_left_sidebar
  end

  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "BIGBAG Store"
    if page_title.empty?
      base_title
    else
      page_title + " - " + base_title
    end
  end
end

app/views/layouts/_copyright.html.erb
<div class="copyRight clearfix">
  <div class="container">
    <div class="row">
      <div class="col-sm-7 col-xs-12">
        <p>&copy; 2017 Copyright Potepan Store .</p>
      </div>
      <div class="col-sm-5 col-xs-12">
        <ul class="list-inline">
          <li>
            <%= link_to 'https://twitter.com/?lang=ja' do %>
              <i class="fa fa-twitter"></i>
            <% end %>
          </li>
          <li>
            <%= link_to 'https://ja-jp.facebook.com/' do %>
              <i class="fa fa-facebook"></i>
            <% end %>
          </li>
          <li>
            <%= link_to 'https://dribbble.com/' do %>
              <i class="fa fa-dribbble"></i>
            <% end %>
          </li>
          <li>
            <%= link_to 'https://vimeo.com/jp' do %>
              <i class="fa fa-vimeo"></i>
            <% end %>
          </li>
          <li>
            <%= link_to 'https://www.tumblr.com/' do %>
              <i class="fa fa-tumblr"></i>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="footer clearfix">
  <div class="container">
    <div class="row">
      <div class="col-sm-2 col-xs-12">
        <div class="footerLink">
          <h5>Accessories</h5>
          <ul class="list-unstyled">
            <li><a href="#">Body care </a></li>
            <li><a href="#">Chambray </a></li>
            <li><a href="#">Floral </a></li>
            <li><a href="#">Rejuvination </a></li>
            <li><a href="#">Shaving </a></li>
            <li><a href="#">Toilette </a></li>
          </ul>
        </div>
      </div>
      <div class="col-sm-2 col-xs-12">
        <div class="footerLink">
          <h5>BRANDS</h5>
          <ul class="list-unstyled">
            <li><a href="#">Barbour </a></li>
            <li><a href="#">Brioni </a></li>
            <li><a href="#">Oliver Spencer</a></li>
            <li><a href="#">Belstaff</a></li>
          </ul>
        </div>
      </div>
      <div class="col-sm-2 col-xs-12">
        <div class="footerLink">
          <h5>Accessories</h5>
          <ul class="list-unstyled">
            <li><a href="#">Body care </a></li>
            <li><a href="#">Chambray </a></li>
            <li><a href="#">Floral </a></li>
            <li><a href="#">Rejuvination </a></li>
            <li><a href="#">Shaving </a></li>
            <li><a href="#">Toilette </a></li>
          </ul>
        </div>
      </div>
      <div class="col-sm-2 col-xs-12">
        <div class="footerLink">
          <h5>Get in Touch</h5>
          <ul class="list-unstyled">
            <li>Call us at (555)-555-5555</li>
            <li><a href="mailto:support@iamabdus.com">support@iamabdus.com</a></li>
          </ul>
        </div>
      </div>
      <div class="col-sm-4 col-xs-12">
        <div class="newsletter clearfix">
          <h4>News letter</h4>
          <h3>Sign up now</h3>
          <p>Enter your email address and get notified about new products. We hate spam!</p>
          <div class="input-group">
            <input type="text" class="form-control" placeholder="your email address" aria-describedby="basic-addon2">
            <a href="#" class="input-group-addon" id="basic-addon2">go <i class="glyphicon glyphicon-chevron-right"></i></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_head.html.erb
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>
  <%= full_title(yield(:title)) %>
</title>
<%= csrf_meta_tags %>
<%= stylesheet_link_tag "application", 'https://fonts.googleapis.com/css?family=Oxygen:400,300,700', :media => "all" %>

app/views/layouts/_header.html.erb
<div class="header clearfix">
  <!-- TOPBAR -->
  <div class="topBar">
    <div class="container">
      <div class="row">
        <div class="col-md-6 hidden-sm hidden-xs">
          <ul class="list-inline">
            <li>
              <%= link_to 'https://twitter.com/?lang=ja' do %>
                <i class="fa fa-twitter"></i>
              <% end %>
            </li>
            <li>
              <%= link_to 'https://ja-jp.facebook.com/' do %>
                <i class="fa fa-facebook"></i>
              <% end %>
            </li>
            <li>
              <%= link_to 'https://dribbble.com/' do %>
                <i class="fa fa-dribbble"></i>
              <% end %>
            </li>
            <li>
              <%= link_to 'https://vimeo.com/jp' do %>
                <i class="fa fa-vimeo"></i>
              <% end %>
            </li>
            <li>
              <%= link_to 'https://www.tumblr.com/' do %>
                <i class="fa fa-tumblr"></i>
              <% end %>
            </li>
          </ul>
        </div>
        <div class="col-md-6 col-xs-12">
          <ul class="list-inline pull-right">
            <li><span><a data-toggle="modal" href='#login'>Log in</a><small>or</small><a data-toggle="modal" href='#signup'>
                  Create an account</a></span></li>
            <li class="dropdown searchBox">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-search"></i></a>
              <ul class="dropdown-menu dropdown-menu-right">
                <li>
                  <span class="input-group">
                    <input type="text" class="form-control" placeholder="Search…" aria-describedby="basic-addon2">
                    <span class="input-group-addon" id="basic-addon2">Search</span>
                  </span>
                </li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-shopping-cart"></i>$0</a>
              <ul class="dropdown-menu dropdown-menu-right">
                <li>Item(s) in your cart</li>
                <li>
                  <a href="#">
                    <div class="media">
                      <%= image_tag("img/home/cart-items/cart-item-01.jpg", :class => "media-left media-object", :alt => "cart-Image") %>
                      <div class="media-body">
                        <h5 class="media-heading">INCIDIDUNT UT <br><span>2 X $199</span></h5>
                      </div>
                    </div>
                  </a>
                </li>
                <li>
                  <a href="#">
                    <div class="media">
                      <%= image_tag("img/home/cart-items/cart-item-01.jpg", :class => "media-left media-object", :alt => "cart-Image") %>
                      <div class="media-body">
                        <h5 class="media-heading">INCIDIDUNT UT <br><span>2 X $199</span></h5>
                      </div>
                    </div>
                  </a>
                </li>
                <li>
                  <div class="btn-group" role="group" aria-label="...">
                    <button type="button" class="btn btn-default">Shopping Cart</button>
                    <button type="button" class="btn btn-default">Checkout</button>
                  </div>
                </li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <!-- NAVBAR -->
  <nav class="navbar navbar-main navbar-default" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to image_tag("img/logo.png"), potepan_index_path,  { :class => "navbar-brand" }  %>
      </div>
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to "Home", potepan_index_path %>
          </li>
          <li class="dropdown megaDropMenu active">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown"
              data-delay="300" data-close-others="true" aria-expanded="false">Shop</a>
            <ul class="dropdown-menu row">
              <li class="col-sm-3 col-xs-12">
                <ul class="list-unstyled">
                  <li>Products Grid View</li>
                  <li>
                    <%= link_to "Categories", potepan_category_path(Spree::Taxon.roots.first.id) %>
                  </li>
                  <li>
                    <%= link_to "Products Sidebar Right", "#" %>
                  </li>
                  <li>
                    <%= link_to "Products 3 Columns V1", "#" %>
                  </li>
                  <li>
                    <%= link_to "Products 3 Columns V2", "#" %>
                  </li>
                  <li>
                    <%= link_to "Products 4 Columns", "#" %>
                  </li>
                </ul>
              </li>
              <li class="col-sm-3 col-xs-12">
                <ul class="list-unstyled">
                  <li>Products List View</li>
                  <li>
                    <%= link_to "Categories", potepan_category_path(Spree::Taxon.roots.first.id) %> <%# FIXME: ここをList表示できるよう修正 %>
                  </li>
                  <li>
                    <%= link_to "Products Sidebar Right", "#" %>
                  </li>
                  <li class="listHeading">Others</li>
                  <li class="active">
                    <%= link_to 'Product Details', potepan_product_path(Spree::Product.first.id) %>
                  </li>
                  <li>
                    <%= link_to 'Cart Page', potepan_cart_page_path %>
                  </li>
                </ul>
              </li>
              <li class="col-sm-3 col-xs-12">
                <ul class="list-unstyled">
                  <li>Checkout</li>
                  <li>
                    <%= link_to 'Step 1 - Address', potepan_checkout_step_1_path %>
                  </li>
                  <li>
                    <%= link_to 'Step 2 - Shipping', potepan_checkout_step_2_path %>
                  </li>
                  <li>
                    <%= link_to 'Step 3 - Payment', potepan_checkout_step_3_path %>
                  </li>
                  <li>
                    <%= link_to 'Order Complete', potepan_checkout_complete_path %>
                  </li>
                </ul>
              </li>
              <li class="col-sm-3 col-xs-12">
                <a href="#" class="menu-photo">
                  <%= image_tag("img/menu-photo.jpg", :alt => "menu-img") %></a>
              </li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
              aria-expanded="false">pages</a>
            <ul class="dropdown-menu dropdown-menu-left">
              <li>
                <%= link_to 'About Us', potepan_about_us_path %>
              </li>
              <li>
                <%= link_to 'Register', '#' %>
              </li>
              <li>
                <%= link_to 'Register or Login', '#' %>
              </li>
              <li>
                <%= link_to 'Login', '#' %>
              </li>
              <li>
                <%= link_to 'Password Recovery', '#' %>
              </li>
              <li>
                <%= link_to 'Privacy Policy', potepan_privacy_policy_path %>
              </li>
              <li>
                <%= link_to 'Terms & Conditions', '#' %>
              </li>
              <li>
                <%= link_to '404 Not Found', '#' %>
              </li>
              <li>
                <%= link_to 'Coming Soon', '#' %>
              </li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
              aria-expanded="false">blog</a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li>
                <%= link_to 'Right Sidebar', potepan_blog_right_sidebar_path %>
              </li>
              <li>
                <%= link_to 'Left Sidebar', potepan_blog_left_sidebar_path %>
              </li>
              <li>
                <%= link_to 'Full Width', '#' %>
              </li>
              <li>
                <%= link_to 'Single Post', '#' %>
              </li>
              <li>
                <%= link_to 'Single Right Sidebar', potepan_blog_single_right_sidebar_path %>
              </li>
              <li>
                <%= link_to 'Single Left Sidebar', potepan_blog_single_left_sidebar_path %>
              </li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
              aria-expanded="false">My Account</a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li>
                <%= link_to 'Dashboard', '#' %>
              </li>
              <li>
                <%= link_to 'Profile', '#' %>
              </li>
              <li>
                <%= link_to 'All Orders', '#' %>
              </li>
              <li>
                <%= link_to 'Single Order', '#' %>
              </li>
              <li>
                <%= link_to 'Wishlist', '#' %>
              </li>
              <li>
                <%= link_to 'Address', '#' %>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</div>

app/views/layouts/_shim.html.erb
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <%= render 'layouts/head' %>
  <%= render 'layouts/shim' %>
</head>

<body>
  <div class="main-wrapper">
    <%= render partial: 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= render 'layouts/copyright' %>
  </div>
  <%= render 'layouts/modal' %>
  <%= javascript_include_tag 'application' %>
</body>

</html>

app/views/potepan/categories/_partners_logo.html.erb
<section class="lightSection clearfix">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="owl-carousel partnersLogoSlider">
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-01.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-02.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-03.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-04.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-05.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-01.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-02.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-03.png", :alt => "partner-img") %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/potepan/categories/_product_category_sidebar.html.erb
<li>
  <a href="javascript:;" data-toggle="collapse" data-target="#<%= taxonomy.id %>">
    <%= taxonomy.name %>
    <i class="fa fa-plus"></i>
  </a>
  <ul id="<%= taxonomy.id %>" class="collapse collapseItem">
    <% taxonomy.taxons.leaves.each do |taxon| %>
      <li>
        <%= link_to potepan_category_path(taxon.id) do %>
          <i class="fa fa-caret-right" aria-hidden="true"></i>
          <%= taxon.name %><span>(<%= taxon.products.size %>)</span>
        <% end %>
      </li>
    <% end %>
  </ul>
</li>

app/views/potepan/categories/_product_grid.html.erb
<div class="col-sm-4 col-xs-12">
  <div class="productBox">
    <div class="productImage clearfix">
      <%= image_tag(product.display_image.attachment.url(:product)) %>
      <div class="productMasking">
        <ul class="list-inline btn-group" role="group">
          <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
          <li><a href="cart_page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
          <li><a class="btn btn-default" data-toggle="modal" href=".quick-view"><i class="fa fa-eye"></i></a></li>
        </ul>
      </div>
    </div>
    <div class="productCaption clearfix">
      <%= link_to potepan_product_path(product.id) do %>
        <h5>
          <%= product.name %>
        </h5>
        <h3>
          <%= product.display_price %>
        </h3>
      <% end %>
    </div>
  </div>
</div>

app/views/potepan/products/_image.html.erb
<div class="item <%= 'active'if image_counter.zero? %>" data-thumb="<%= image_counter %>">
  <%= image_tag(image.attachment.url(:large)) %>
</div>

app/views/potepan/products/_related_product.html.erb
<div class="col-md-3 col-sm-6 col-xs-12">
  <div class="productBox">
    <div class="productImage clearfix">
      <%= image_tag(related_product.display_image.attachment.url(:product)) %>
      <div class="productMasking">
        <ul class="list-inline btn-group" role="group">
          <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
          <li><a href="cart_page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
          <li><a class="btn btn-default" data-toggle="modal" href=".quick-view"><i class="fa fa-eye"></i></a></li>
        </ul>
      </div>
    </div>
    <div class="productCaption clearfix">
      <%= link_to potepan_product_path(related_product.id) do %>
        <h5>
          <%= related_product.name %>
        </h5>
        <h3>
          <%= related_product.display_price %>
        </h3>
      <% end %>
    </div>
  </div>
</div>

app/views/potepan/products/_thumbnail.html.erb
<div data-target="#carousel" data-slide-to="<%= image_counter %>" class="thumb">
  <%= image_tag(image.attachment.url(:product)) %>
</div>

app/views/potepan/products/show.html.erb
<% provide(:title, @product.name)%>
<!-- LIGHT SECTION -->
<%= render partial: 'shared/page_header' %>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix">
  <div class="container">
    <div class="row singleProduct">
      <div class="col-xs-12">
        <div class="media">
          <div class="media-left productSlider">
            <div id="carousel" class="carousel slide" data-ride="carousel">
              <div class="carousel-inner">
                <%= render partial: 'image', collection: @product.images %>
              </div>
            </div>
            <div class="clearfix">
              <div id="thumbcarousel" class="carousel slide" data-interval="false">
                <div class="carousel-inner">
                  <%= render partial: 'thumbnail', collection: @product.images, as: :image %>
                </div>
                <a class="left carousel-control" href="#thumbcarousel" role="button" data-slide="prev">
                  <span class="glyphicon glyphicon-chevron-left"></span>
                </a>
                <a class="right carousel-control" href="#thumbcarousel" role="button" data-slide="next">
                  <span class="glyphicon glyphicon-chevron-right"></span>
                </a>
              </div>
            </div>
          </div>
          <div class="media-body">
            <ul class="list-inline">
              <li>
                <%= link_to potepan_category_path(@product.taxon_ids.first) do %>
                  <i class="fa fa-reply" aria-hidden="true"></i>一覧ページへ戻る
                <% end %>
              </li>
            </ul>
            <h2>
              <%= @product.name %>
            </h2>
            <h3>
              <%= @product.display_price %>
            </h3>
            <p>
              <%= @product.description %>
            </p>
            <span class="quick-drop">
              <select name="guiest_id3" id="guiest_id3" class="select-drop">
                <option value="0">S</option>
                <option value="1">M</option>
                <option value="2">L</option>
                <option value="3">XL</option>
              </select>
            </span>
            <span class="quick-drop resizeWidth">
              <select name="guiest_id4" id="guiest_id4" class="select-drop">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
              </select>
            </span>
            <div class="btn-area">
              <a href="cart_page.html" class="btn btn-primary btn-block">カートへ入れる<i class="fa fa-angle-right"
                  aria-hidden="true"></i></a>
            </div>
            <div class="tabArea">
              <ul class="nav nav-tabs">
                <li class="active"><a data-toggle="tab" href="#details">details</a></li>
                <li><a data-toggle="tab" href="#about-art">about art</a></li>
                <li><a data-toggle="tab" href="#sizing">sizing</a></li>
                <li><a data-toggle="tab" href="#shipping">shipping</a></li>
              </ul>
              <div class="tab-content">
                <div id="details" class="tab-pane fade in active">
                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut
                    labore et dolore magna aliqua.</p>
                  <ul class="list-unstyled">
                    <li>Black, Crew Neck</li>
                    <li>75% Cotton, 25% Rayon</li>
                    <li>Waterbased Ink</li>
                    <li>Wash Cold, dry low</li>
                  </ul>
                </div>
                <div id="about-art" class="tab-pane fade">
                  <p>Nulla facilisi. Mauris efficitur, massa et iaculis accumsan, mauris velit ultrices purus, quis
                    condimentum nibh dolor ut tortor. Donec egestas tortor quis mattis gravida. Ut efficitur elit
                    vitae dignissim volutpat. </p>
                </div>
                <div id="sizing" class="tab-pane fade">
                  <p>Praesent dui felis, gravida a auctor at, facilisis commodo ipsum. Cras eu faucibus justo. Nullam
                    varius cursus nisi, sed elementum sem sagittis at. Nulla tellus massa, vestibulum a commodo
                    facilisis, pulvinar convallis nunc.</p>
                </div>
                <div id="shipping" class="tab-pane fade">
                  <p>Mauris lobortis augue ex, ut faucibus nisi mollis ac. Sed volutpat scelerisque ex ut
                    ullamcorper. Cras at velit quis sapien dapibus laoreet a id odio. Sed sit amet accumsan ante, eu
                    congue metus. Aenean eros tortor, cursus quis feugiat sed, vestibulum vel purus.</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row productsContent">
      <div class="col-xs-12">
        <div class="page-header">
          <h4>関連商品</h4>
        </div>
      </div>
        <%= render partial: 'related_product', collection: @related_products %>
    </div>
  </div>
</section>

app/views/potepan/sample/_category_link.html.erb
<li class="col-sm-3 col-xs-12">
  <ul class="list-unstyled">
    <li>
      <%= link_to potepan_category_path(taxonomy.id) do %>
        <%= taxonomy.name %>
      <% end %>
      <ul class="list-unstyled">
        <li>
          <% taxonomy.taxons.leaves.each do |taxon| %>
            <%= link_to potepan_category_path(taxon.id) do %>
              <i class="fa fa-caret-right" aria-hidden="true"></i>
              <%= taxon.name %><span>(<%= taxon.products.count %>)</span>
            <% end %>
          <% end %>
        </li>
      </ul>
    </li>
  </ul>
</li>

app/views/shared/_page_header.html.erb
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2>
            <%= yield(:title) %>
          </h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <%= link_to 'Home', potepan_root_path %>
          </li>
          <li>
            <a href="#">shop</a>
          </li>
          <li class="active">
            <%= yield(:title) %>
          </li>
        </ol>
      </div>
    </div>
  </div>
</section>